export const walletOne = [
  {
    id: 1,
    address: "bc1qrrmqpycc5fm8eh6mkyjpgpn4fa0sweu3pkvh8r",
    sym: "BTC",
    name: "bitcoin",
    img: "",
  },
  {
    id: 2,
    address: "0xC8E9b328100E8D13AfC32B501B4113715d5fE5Aa",
    sym: "ETH",
    name: "Ethereum",
    img: "",
  },
  {
    id: 6,
    address: "0x42501d8F55FCdcb368B97E0AF0271a8F6f615cFc",
    sym: "USDT ETH",
    name: "Tether",
    img: "",
  },
  {
    id: 3,
    address: "44SbUCJzyApxb7W7PfLwaMdzqwxhtCTPgRd7EQgMa3rM",
    sym: "USDT SOL",
    name: "Tether",
    img: "",
  },
  {
    id: 3,
    address: "TRDj93pVxQabWGXnF75iSGBUtAyJJcF97e",
    sym: "USDT TRC20",
    name: "Tether",
    img: "",
  },
  // {
  //   id: 5,
  //   address: "rN1HNVvdrQwx6A2wBs1PCMD5GRdKCehWEc",
  //   sym: "XRP",
  //   name: "Ripple",
  //   img: "/wallets/xrp.jpeg",
  // },
  // {
  //   id: 6,
  //   address: "ltc1q6s4fw626xutm3mkehcytyx6lxaxengdeyjan47",
  //   sym: "LTC",
  //   name: "litecoin",
  //   img: "/wallets/xrp.jpeg",
  // },
];

export const walletTwo = [
  {
    id: 1,
    address: "bc1qglpn5c30rgr9kzrhhdyamff53pxuahzt75k9kf",
    sym: "BTC",
    name: "bitcoin",
    img: "/wallets/btc.jpeg",
  },
  {
    id: 2,
    address: "0xE7a102A57DA67C1513C3C40B9BD0a299D59e70cb",
    sym: "ETH",
    name: "Ethereum",
    img: "/wallets/eth.jpeg",
  },
  {
    id: 6,
    address: "0xDF09ba09E8F975b7dBb11002dD0E1D7c10296789",
    sym: "USDT ETH",
    name: "Tether",
    img: "/wallets/eth.jpeg",
  },
  // {
  //   id: 3,
  //   address: "9ngy4uU5tWX1FePVMiNXVyvqfaq2LLaLHeCfYuEJRUG1",
  //   sym: "USDT SOL",
  //   name: "Tether",
  //   img: "/wallets/usdt2.jpeg",
  // },
  {
    id: 5,
    address: "rN1HNVvdrQwx6A2wBs1PCMD5GRdKCehWEc",
    sym: "XRP",
    name: "Ripple",
    img: "/wallets/xrp.jpeg",
  },
  {
    id: 6,
    address: "ltc1q6s4fw626xutm3mkehcytyx6lxaxengdeyjan47",
    sym: "LTC",
    name: "litecoin",
    img: "/wallets/xrp.jpeg",
  },
];
